### ISSUE TITLE
Figuring out how to add the submodule. 

### ISSUE THREAD

**Issue by Plikt** [DeSci-md/automating-metadata#11]
I have added the submodule for PDFMetadataExtractor on my machine. However, while it says that I have successfully added the submodule, I can't find that module anywhere in the Git and the little arrow file that @Gizmotronn said would exist isn't showing up. What am I missing here?

**Comment by Gizmotronn** [comment]
Hey @Plikt , will review this ASAP before the next meeting. Actually, I think I'll bring it in myself and push.

**Comment by Plikt** [comment]
Figured this out and put it in!
